name: Jiangsterpluginsnow
main: ifteam\SnowHalation\SnowHalation
version: 1.8-alpha
author: hm
api:
- 1.13.0
- 2.0.0

commands:
 snow:
   permission: snowhalation
   description: SnowHalation control commands
   usage: /snow

permissions:
 snowhalation:
  default: true
  description: Allows commands of SnowHalation
